#include <stdio.h>
#include <unistd.h>
#include <termios.h>

/* 终端标志位: TOSTOP, POSIX.1
 * If set and if the implementation supports job control, the SIGTTOU
 * signal is sent to the process group of a background process that tries
 * to write its controlling terminal. By default, this signal stops all
 * the processes in the process group. This signal is not generated by
 * the terminal driver if the background process that is writing to the
 * controlling terminal is either ignoring or blocking the signal.
 */
int main(void)
{
    struct termios term;

    if (tcgetattr(STDIN_FILENO, &term) < 0) {
        perror("tcgetattr STDIN_FILENO error");
        return 1;
    }

    /* 从执行结果看,终端默认没有设置该标志位 */
    printf("term.c_lflag: %#x, TOSTOP: %#x, &= %#x\n",
            term.c_lflag, TOSTOP, term.c_lflag & TOSTOP);

    return 0;
}
