.PHONY: all do

%: %.c
	gcc -Wall -o $@ $<

all: utime do

utime: utime.c

do:
	echo -e '\033[32mEXECUTE TNE BIN !!!\033[0m'
	ls -l tian xia
	./utime tian xia
	ls -l tian xia
	ls -lu tian xia
	ls -lc tian xia
